name: libnomp-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - doxygen
  - pip
  - pip:
    - -r requirements.txt
    - breathe==4.34.0
    - Sphinx==5.1.1
    - sphinx-rtd-theme==1.0.0
    - clang-format==14.0.6
    - isort==5.10.1
    - black==22.8.0
    - flake8==4.0.1
